# 📐 Linear Algebra for ML — Guided Exercises
**VS Code | Python beginner-friendly | Step-by-step hints included**

---
### How to use this notebook
- Each exercise has a **Goal**, **Hint** (step-by-step), and a **Check** cell
- Write your code in the `# YOUR CODE` section
- Run the Check cell to verify your answer
- If stuck → read the hint, try again before looking at answers

```
Run a cell:  Shift + Enter
New cell:    Press B (below) or A (above)
```

---
## 🔧 Setup — Run this first every session

In [3]:
import numpy as np

# Helper: prints arrays nicely
def show(name, val):
    if isinstance(val, np.ndarray):
        print(f"\n{name} (shape={val.shape}):")
        print(np.round(val, 4))
    else:
        print(f"\n{name} = {round(float(val), 6)}")

# Helper: auto-grade
def check(label, got, expected, tol=1e-3):
    got_arr = np.array(got, dtype=float)
    exp_arr = np.array(expected, dtype=float)
    if np.allclose(got_arr, exp_arr, atol=tol):
        print(f"  ✅ {label}: CORRECT")
    else:
        print(f"  ❌ {label}: got {np.round(got_arr,4)}, expected {np.round(exp_arr,4)}")

print("Setup ready! NumPy:", np.__version__)

Setup ready! NumPy: 2.4.3


---
## MODULE 1 — Vectors

**Mental model:** A vector is just a list of numbers that describes one thing.
In ML, one data point (e.g., one house, one person) = one vector.

```
Person = [height=1.75, weight=80, neck=46, waist=102, age=45]
         ↑ this is a 5-dimensional vector
```

### Exercise 1-A: Create a vector and check its shape

**Goal:** Create a vector describing one person, then inspect it.

**Hint (step by step):**
```
Step 1: Use np.array([...]) with the 5 values
Step 2: .shape tells you the dimensions → should be (5,)
Step 3: len() gives number of elements
```

In [4]:
# Person: height=1.75m, weight=80kg, neck=46cm, waist=102cm, age=45

# Step 1: Create the vector
person = np.array([1.75, 80, 46, 102, 45])

# Step 2: Print shape and length
print("Values:", person)
print("Shape: ", person.shape)   # (5,) means 5 elements, 1 dimension
print("Length:", len(person))

# Step 3: Access individual elements (index starts at 0!)
print("\nHeight (index 0):", person[0])
print("Age    (index 4):", person[4])

Values: [  1.75  80.    46.   102.    45.  ]
Shape:  (5,)
Length: 5

Height (index 0): 1.75
Age    (index 4): 45.0


### Exercise 1-B: Column vector vs Row vector

**Goal:** Understand the difference between shape `(5,)`, `(5,1)`, and `(1,5)`.

**Why it matters:**  
In Linear Regression, `w` must be a column `(N,1)` to multiply with `X` correctly.  
Wrong shape → error.

**Hint:**
```
Step 1: reshape(5, 1)  → column vector  (5 rows, 1 col)
Step 2: reshape(1, 5)  → row vector     (1 row,  5 cols)
Step 3: .T on a 2D array flips rows/cols
Shortcut: reshape(-1, 1) means "figure out rows automatically"
```

In [6]:
person = np.array([1.75, 80, 46, 102, 45])

# YOUR CODE: create column and row versions
col = person.reshape(5, 1)    # or reshape(-1, 1)
row = person.reshape(1, 5)    # or reshape(1, -1)

show("Original (5,)",  person)
show("Column (5,1)",   col)
show("Row    (1,5)",   row)

print("\nTranspose of col == row?", np.allclose(col.T, row))  # True


Original (5,) (shape=(5,)):
[  1.75  80.    46.   102.    45.  ]

Column (5,1) (shape=(5, 1)):
[[  1.75]
 [ 80.  ]
 [ 46.  ]
 [102.  ]
 [ 45.  ]]

Row    (1,5) (shape=(1, 5)):
[[  1.75  80.    46.   102.    45.  ]]

Transpose of col == row? True


In [7]:
# ✅ Check
check("col shape rows",  col.shape[0],  5)
check("col shape cols",  col.shape[1],  1)
check("row shape rows",  row.shape[0],  1)
check("row shape cols",  row.shape[1],  5)
check("col.T == row",    col.T,          row)

  ✅ col shape rows: CORRECT
  ✅ col shape cols: CORRECT
  ✅ row shape rows: CORRECT
  ✅ row shape cols: CORRECT
  ✅ col.T == row: CORRECT


---
## MODULE 2 — Matrices

**Mental model:** A matrix is a table of numbers.  
In ML, the **design matrix X** stacks all your data points:
```
Row = one feature
Col = one sample (person / house / etc.)
```

### Exercise 2-A: Build a data matrix

**Goal:** Store 3 people × 5 measurements as a matrix, then transpose it.

**Hint:**
```
Step 1: np.array([[row1], [row2], [row3]]) → shape (3, 5)
Step 2: .T flips to shape (5, 3) = design matrix format
Step 3: access element [row, col]
```

In [8]:
# 3 people, 5 measurements each
# Person 1: height=1.50, weight=75.2, neck=41.3, waist=81.28, age=35.5
# Person 2: height=1.75, weight=80.6, neck=46.7, waist=102.5, age=45.0
# Person 3: height=1.82, weight=69.3, neck=42.5, waist=83.5,  age=30.0

# YOUR CODE: create a (3, 5) matrix called 'people'
people = np.array([
    [1.50, 75.2, 41.3,  81.28, 35.5],
    [1.75, 80.6, 46.7, 102.5,  45.0],
    [1.82, 69.3, 42.5,  83.5,  30.0],
])

print("people shape:", people.shape)   # (3, 5): 3 rows=people, 5 cols=features

# Transpose → design matrix: features as rows, people as columns
X = people.T
print("X shape:",      X.shape)        # (5, 3): 5 rows=features, 3 cols=people

# Access specific elements
print("\nPerson 2, neck (row=1, col=2):", people[1, 2])   # 46.7
print("All heights (feature row=0):",     X[0, :])         # [1.50, 1.75, 1.82]

people shape: (3, 5)
X shape: (5, 3)

Person 2, neck (row=1, col=2): 46.7
All heights (feature row=0): [1.5  1.75 1.82]


In [9]:
# ✅ Check
check("people shape",    list(people.shape),   [3, 5])
check("X shape",         list(X.shape),        [5, 3])
check("person2 neck",    people[1, 2],          46.7)
check("all heights",     X[0, :],              [1.50, 1.75, 1.82])

  ✅ people shape: CORRECT
  ✅ X shape: CORRECT
  ✅ person2 neck: CORRECT
  ✅ all heights: CORRECT


### Exercise 2-B: Special matrices

**Goal:** Build identity, diagonal, and check symmetry.

**Why it matters:**
- Identity `I`: appears in Ridge as `(XXᵀ + λI)` — shifts eigenvalues
- Diagonal `Λ`: stores eigenvalues in PCA
- Symmetric: covariance matrices are always symmetric

**Hint:**
```
np.eye(n)          → identity n×n
np.diag([a,b,c])   → diagonal matrix
np.allclose(M, M.T)→ check symmetry
```

In [ ]:
# YOUR CODE

# 1. Identity matrix 4×4
I4 = np.eye(4)
show("Identity 4x4", I4)

# 2. Diagonal matrix diag(4, 6, 2, 1)
D = np.diag([4, 6, 2, 1])
show("Diagonal", D)

# 3. Verify: any matrix M × I = M
M = np.array([[2.0, 3.0], [5.0, 7.0]])
result = M @ np.eye(2)         # @ is matrix multiply
print("\nM @ I == M?", np.allclose(result, M))   # True

# 4. Check if this matrix is symmetric
C = np.array([[1, 2, 4],
              [2, 5, 8],
              [4, 8, 7]])
print("C symmetric?", np.allclose(C, C.T))       # True

---
## MODULE 3 — Matrix Multiplication

**Mental model:**
```
A (m×n)  @  B (n×d)  =  C (m×d)
       ↑       ↑
     must match!

C[i,j] = dot product of ROW i of A  with  COLUMN j of B
```

In Linear Regression: **prediction = Xᵀ @ W**  
→ you multiply your data matrix by your weight vector to get predictions.

### Exercise 3-A: Multiply step by step

**Goal:** Compute a matrix product and verify two specific entries by hand.

**Hint:**
```
Step 1: A @ B  → numpy does the whole product
Step 2: C[0,0] = sum of (row 0 of A) × (col 0 of B), element by element
        = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0] + A[0,3]*B[3,0]
Step 3: index into C to get the same entry and compare
```

In [10]:
A = np.array([
    [4.6, 5.7, 6.1, 5.5],
    [2.4, 3.6, 4.7, 4.9],
    [3.5, 5.3, 9.5, 8.5],
])  # shape (3, 4)

B = np.array([
    [3.5, 6.2, 1.0],
    [1.5, 3.7, 3.3],
    [4.1, 8.7, 7.5],
    [7.5, 4.1, 9.5],
])  # shape (4, 3)

# YOUR CODE

# Step 1: Full matrix product
C = A @ B
show("C = A @ B", C)

# Step 2: Manually compute C[0,0] (row 0 of A · col 0 of B)
c00_manual = 4.6*3.5 + 5.7*1.5 + 6.1*4.1 + 5.5*7.5
print("\nc[0,0] manual:", round(c00_manual, 2))    # expected: 90.91
print("c[0,0] numpy: ", round(C[0, 0], 2))         # expected: 90.91

# Step 3: Manually compute C[2,1] (row 2 of A · col 1 of B)
c21_manual = 3.5*6.2 + 5.3*3.7 + 9.5*8.7 + 8.5*4.1
print("\nc[2,1] manual:", round(c21_manual, 2))     # expected: 158.81
print("c[2,1] numpy: ", round(C[2, 1], 2))          # expected: 158.81


C = A @ B (shape=(3, 3)):
[[ 90.91 125.23 121.41]
 [ 69.82  89.18  96.08]
 [122.9  158.81 172.99]]

c[0,0] manual: 90.91
c[0,0] numpy:  90.91

c[2,1] manual: 158.81
c[2,1] numpy:  158.81


In [11]:
# ✅ Check
check("C shape rows",  C.shape[0],   3)
check("C shape cols",  C.shape[1],   3)
check("C[0,0]",        C[0,0],       90.91)
check("C[2,1]",        C[2,1],       158.81)

  ✅ C shape rows: CORRECT
  ✅ C shape cols: CORRECT
  ✅ C[0,0]: CORRECT
  ✅ C[2,1]: CORRECT


### Exercise 3-B: AB ≠ BA  (non-commutativity)

**Goal:** Prove that the order of multiplication matters.

**Hint:**
```
Step 1: Compute AB
Step 2: Compute BA  
Step 3: np.allclose(AB, BA) will be False
```

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# YOUR CODE
AB = A @ B
BA = B @ A

print("AB =\n", AB)                          # [[19,22],[43,50]]
print("\nBA =\n", BA)                        # [[23,34],[31,46]]
print("\nAB == BA?", np.allclose(AB, BA))    # False!

AB =
 [[19 22]
 [43 50]]

BA =
 [[23 34]
 [31 46]]

AB == BA? False


### Exercise 3-C: Transpose rule  (AB)ᵀ = BᵀAᵀ

**Goal:** Verify this rule — it appears constantly in ML derivations.

**Hint:**
```
Step 1: Compute AB, then take transpose → (AB).T
Step 2: Compute B.T @ A.T
Step 3: Check they are equal with np.allclose
```

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6]])          # (2, 3)
B = np.array([[7, 8], [9, 10], [11, 12]])      # (3, 2)

# YOUR CODE
left_side  = (A @ B).T        # (AB)ᵀ
right_side = B.T @ A.T        # BᵀAᵀ

print("(AB)ᵀ =\n",  left_side)
print("\nBᵀAᵀ =\n", right_side)
print("\nRule holds?", np.allclose(left_side, right_side))   # True

(AB)ᵀ =
 [[ 58 139]
 [ 64 154]]

BᵀAᵀ =
 [[ 58 139]
 [ 64 154]]

Rule holds? True


---
## MODULE 4 — Inner Product, Norms

**Mental model:**
```
Inner product:  xᵀy = one number that measures similarity
Norm ‖x‖:       length of vector x

In ML:
  Ridge penalty = ‖w‖²  = sum(wᵢ²)    (L2)
  Lasso penalty = ‖w‖₁  = sum(|wᵢ|)   (L1)
```

### Exercise 4-A: Dot product three ways

**Goal:** Compute the inner product of x and y, using 3 different methods.

**Hint:**
```
Method 1: np.dot(x, y)
Method 2: x @ y          (@ works for 1D arrays too)
Method 3: np.sum(x * y)  (multiply element-wise, then sum)
All three should give 76.
```

In [14]:
x = np.array([1, 3, 4, 6, 8])
y = np.array([5, 1, 0, 2, 7])

# YOUR CODE
m1 = np.dot(x, y)         # method 1
m2 = x @ y                # method 2
m3 = np.sum(x * y)        # method 3: element-wise × then sum

print("Method 1 (np.dot):", m1)    # 76
print("Method 2 (@):     ", m2)    # 76
print("Method 3 (manual):", m3)    # 76

# Manually verify one step at a time:
print("\nManual: 1×5 + 3×1 + 4×0 + 6×2 + 8×7")
print("      =", 1*5, "+", 3*1, "+", 4*0, "+", 6*2, "+", 8*7, "=", 1*5+3*1+4*0+6*2+8*7)

Method 1 (np.dot): 76
Method 2 (@):      76
Method 3 (manual): 76

Manual: 1×5 + 3×1 + 4×0 + 6×2 + 8×7
      = 5 + 3 + 0 + 12 + 56 = 76


In [16]:
# ✅ Check
check("dot product", m1, 76)
check("@ operator",  m2, 76)
check("manual sum",  m3, 76)

  ✅ dot product: CORRECT
  ✅ @ operator: CORRECT
  ✅ manual sum: CORRECT


### Exercise 4-B: Euclidean norm (length)

**Goal:** Compute ‖x‖ = √(x₁² + x₂² + ... + xd²)

**Hint:**
```
Step 1: Square each element:  x ** 2
Step 2: Sum them:             np.sum(x**2)
Step 3: Take square root:     np.sqrt(...)
Shortcut:                     np.linalg.norm(x)
```

In [17]:
x = np.array([1, 3, 4, 6, 8], dtype=float)
y = np.array([5, 1, 0, 2, 7], dtype=float)

# YOUR CODE

# Manual: sqrt( 1²+3²+4²+6²+8² )
norm_x_manual = np.sqrt(np.sum(x ** 2))
norm_x_numpy  = np.linalg.norm(x)

norm_y_manual = np.sqrt(np.sum(y ** 2))
norm_y_numpy  = np.linalg.norm(y)

print(f"‖x‖ manual: {norm_x_manual:.4f}")    # 11.2250
print(f"‖x‖ numpy:  {norm_x_numpy:.4f}")     # 11.2250
print(f"‖y‖ manual: {norm_y_manual:.4f}")    # 8.8882

# Normalise x (make its length = 1)
x_unit = x / norm_x_numpy
print(f"\n‖x_unit‖ = {np.linalg.norm(x_unit):.6f}")   # should be 1.0

‖x‖ manual: 11.2250
‖x‖ numpy:  11.2250
‖y‖ manual: 8.8882

‖x_unit‖ = 1.000000


In [18]:
# ✅ Check
check("‖x‖",             norm_x_numpy,  11.225, tol=0.01)
check("‖y‖",             norm_y_numpy,  8.888,  tol=0.01)
check("‖x_unit‖",        np.linalg.norm(x_unit), 1.0)

  ✅ ‖x‖: CORRECT
  ✅ ‖y‖: CORRECT
  ✅ ‖x_unit‖: CORRECT


### Exercise 4-C: Angle between vectors

**Goal:** Compute the angle θ between x and y.

**Hint:**
```
Formula: cos θ = xᵀy / (‖x‖ · ‖y‖)
Step 1: Compute dot product
Step 2: Compute both norms
Step 3: cos_theta = dot / (norm_x * norm_y)
Step 4: theta = np.arccos(cos_theta)   → radians
Step 5: np.degrees(theta)              → convert to degrees
```

In [19]:
x = np.array([1, 3, 4, 6, 8], dtype=float)
y = np.array([5, 1, 0, 2, 7], dtype=float)

# YOUR CODE
dot_xy    = np.dot(x, y)                         # step 1
norm_x    = np.linalg.norm(x)                    # step 2a
norm_y    = np.linalg.norm(y)                    # step 2b
cos_theta = dot_xy / (norm_x * norm_y)           # step 3
theta_rad = np.arccos(cos_theta)                 # step 4
theta_deg = np.degrees(theta_rad)                # step 5

print(f"dot(x,y)  = {dot_xy}")
print(f"cos θ     = {cos_theta:.4f}")    # ~0.7613
print(f"θ (rad)   = {theta_rad:.4f}")    # ~0.7074
print(f"θ (deg)   = {theta_deg:.2f}°")   # ~40.5°

# Are they orthogonal? (dot = 0 means perpendicular)
print(f"\nOrthogonal? {np.isclose(dot_xy, 0)}")   # False

dot(x,y)  = 76.0
cos θ     = 0.7618
θ (rad)   = 0.7048
θ (deg)   = 40.38°

Orthogonal? False


### Exercise 4-D: L1 vs L2 norm  (Lasso vs Ridge)

**Goal:** Understand why the choice of norm changes the penalty behavior.

**Hint:**
```
L2 norm:   ‖w‖  = sqrt(sum(wᵢ²))     → np.linalg.norm(w)
L2 norm²:  ‖w‖² = sum(wᵢ²)           → Ridge penalty
L1 norm:   ‖w‖₁ = sum(|wᵢ|)          → Lasso penalty
           np.sum(np.abs(w))
```

In [ ]:
# Two weight vectors: one has a near-zero value, one is spread out
w_sparse = np.array([2.0, 0.0, 0.0, 0.01, 0.0])   # mostly zeros
w_spread = np.array([0.4, 0.4, 0.4, 0.41, 0.4])   # spread across features

for name, w in [("w_sparse", w_sparse), ("w_spread", w_spread)]:
    l2_penalty = np.sum(w ** 2)            # Ridge: sum of squares
    l1_penalty = np.sum(np.abs(w))         # Lasso: sum of absolute values
    print(f"{name}: L2 penalty = {l2_penalty:.4f}  |  L1 penalty = {l1_penalty:.4f}")

print("""
Observation:
  L2 (Ridge): heavily penalises LARGE values, tolerates many small ones
  L1 (Lasso): penalises equally per unit → prefers fewer non-zero weights
  → L1 pushes weights exactly to 0 (sparse solution)
  → L2 shrinks weights but rarely to exactly 0
""")

---
## MODULE 5 — Determinant and Inverse

**Mental model:**
```
Determinant: one number that tells you if a matrix is invertible
  det ≠ 0  →  invertible  →  unique solution exists
  det = 0  →  singular    →  no solution (or infinite solutions)

Inverse M⁻¹: like dividing — M⁻¹ @ M = I

Linear Regression: W* = (XXᵀ)⁻¹ XY
  → needs (XXᵀ) to be invertible!
  Ridge fixes this: (XXᵀ + λI) is ALWAYS invertible
```

### Exercise 5-A: Compute and interpret the determinant

**Hint:**
```
np.linalg.det(M)   → determinant
det ≠ 0 → invertible
det = 0 → singular (no inverse)
```

In [ ]:
# Matrix from the lecture
A = np.array([[2,  4,  6],
              [-1, 2,  3],
              [1,  4,  9]], dtype=float)

# A singular matrix: row 2 = 2 × row 1 → redundant!
A_sing = np.array([[1, 2],
                   [2, 4]], dtype=float)

# YOUR CODE
det_A      = np.linalg.det(A)
det_A_sing = np.linalg.det(A_sing)

print(f"det(A)         = {det_A:.1f}")        # 24.0 → invertible
print(f"det(A_singular)= {det_A_sing:.6f}")   # 0.0  → not invertible

print(f"\nA invertible?       {not np.isclose(det_A,      0)}")  # True
print(f"A_sing invertible?  {not np.isclose(det_A_sing,  0)}")  # False

# Property: product of eigenvalues = determinant
eigs, _ = np.linalg.eig(A)
print(f"\nProduct of eigenvalues: {np.prod(eigs).real:.2f}")   # should match det
print(f"Determinant:            {det_A:.2f}")

In [ ]:
# ✅ Check
check("det(A)",       det_A,      24.0)
check("det(A_sing)",  det_A_sing, 0.0, tol=1e-9)

### Exercise 5-B: Compute the inverse and verify

**Hint:**
```
Step 1: np.linalg.inv(A)  → compute inverse
Step 2: A @ A_inv         → should give identity matrix
Step 3: np.allclose(A @ A_inv, np.eye(3))  → verify
```

In [ ]:
A = np.array([[2,  4,  6],
              [-1, 2,  3],
              [1,  4,  9]], dtype=float)

# YOUR CODE
A_inv = np.linalg.inv(A)
show("A_inv", A_inv)

# Verify: A @ A_inv should = I
product = A @ A_inv
print("\nA @ A_inv =\n", np.round(product, 6))
print("Is identity?", np.allclose(product, np.eye(3)))   # True

# Rule: (AB)⁻¹ = B⁻¹ A⁻¹
B = np.array([[1, 0, 2], [0, 1, 0], [3, 0, 1]], dtype=float)
left  = np.linalg.inv(A @ B)
right = np.linalg.inv(B) @ np.linalg.inv(A)
print("\n(AB)⁻¹ == B⁻¹A⁻¹?", np.allclose(left, right))  # True

### Exercise 5-C: Why Ridge always has a solution

**Goal:** Show that adding λI to XXᵀ makes it always invertible.

**Hint:**
```
Step 1: Create X where the rows are linearly dependent
        → XXᵀ will be singular (det=0)
Step 2: Add λI  → (XXᵀ + λI) → det > 0 → invertible
Step 3: Print eigenvalues to see why:
        eigenvalues of XXᵀ  include 0
        eigenvalues of (XXᵀ + λI)  = previous + λ  (all > 0)
```

In [ ]:
# X where row 2 = 2 × row 1 (linearly dependent → rank 1)
X = np.array([[1, 2, 3],
              [2, 4, 6]], dtype=float)

XXT = X @ X.T                  # shape (2, 2)
lam = 1.0

# YOUR CODE
XXT_ridge = XXT + lam * np.eye(XXT.shape[0])

det_XXT       = np.linalg.det(XXT)
det_XXT_ridge = np.linalg.det(XXT_ridge)

print(f"det(XXT)          = {det_XXT:.4f}")       # 0.0 → singular!
print(f"det(XXT + λI)     = {det_XXT_ridge:.4f}")  # > 0  → invertible

eigs_before = np.linalg.eigvalsh(XXT)
eigs_after  = np.linalg.eigvalsh(XXT_ridge)
print(f"\nEigenvalues of XXT      : {np.round(eigs_before, 4)}")   # includes 0
print(f"Eigenvalues of XXT+λI   : {np.round(eigs_after,  4)}")    # all > 0
print("\nConclusion: adding λI shifts every eigenvalue by λ → no zeros → always invertible")

---
## MODULE 6 — Eigenvalues & Eigenvectors

**Mental model:**
```
For matrix M:  M @ u = λ @ u

u = eigenvector:  a special direction that M doesn't rotate
λ = eigenvalue:   how much M stretches along that direction

In PCA: eigenvectors = principal component directions
        eigenvalues  = how much variance in each direction
```

### Exercise 6-A: Compute and verify eigenpairs

**Hint:**
```
Step 1: np.linalg.eig(M)   → returns (eigenvalues, eigenvectors)
        eigenvectors are columns of the returned matrix
Step 2: Extract i-th eigenvector: vecs[:, i]
Step 3: Verify: M @ u  should equal  λ * u
        np.allclose(M @ u, lam * u)  should be True
```

In [ ]:
M = np.array([[3.0, 1.0],
              [0.0, 2.0]])

# YOUR CODE
eigenvalues, eigenvectors = np.linalg.eig(M)

print("Eigenvalues:",  np.round(eigenvalues, 4))     # [3.0, 2.0]
print("Eigenvectors (columns):\n", np.round(eigenvectors, 4))

# Verify M @ u = λ * u for each pair
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    u   = eigenvectors[:, i]    # i-th column
    Mu  = M @ u
    lu  = lam * u
    ok  = np.allclose(Mu, lu)
    print(f"\nPair {i+1}: λ={lam:.1f}")
    print(f"  M @ u  = {np.round(Mu, 4)}")
    print(f"  λ × u  = {np.round(lu, 4)}")
    print(f"  Match? {ok}")

### Exercise 6-B: Properties — sum, product, trace

**Hint:**
```
Property 1: product of eigenvalues = determinant
Property 2: sum of eigenvalues = trace
Property 3: all eigenvalues > 0 → matrix is PD → gradient descent converges
```

In [ ]:
M = np.array([[4.0, 2.0],
              [1.0, 3.0]])

# YOUR CODE
eigs, _ = np.linalg.eig(M)

# Property 1: product of eigenvalues = det
prod_eigs = np.prod(eigs)
det_M     = np.linalg.det(M)
print(f"Product of eigenvalues: {prod_eigs.real:.4f}")
print(f"Determinant:            {det_M:.4f}")
print(f"Match? {np.isclose(prod_eigs.real, det_M)}")

# Property 2: sum of eigenvalues = trace
sum_eigs = np.sum(eigs)
trace_M  = np.trace(M)
print(f"\nSum of eigenvalues: {sum_eigs.real:.4f}")
print(f"Trace:              {trace_M:.4f}")
print(f"Match? {np.isclose(sum_eigs.real, trace_M)}")

# Property 3: PD check
print(f"\nAll eigenvalues > 0? {np.all(eigs.real > 0)}  → M is PD")

### Exercise 6-C: Eigendecomposition  M = UΛUᵀ

**Hint:**
```
Step 1: np.linalg.eigh(M)  → for symmetric M, returns sorted real eigenvalues
Step 2: np.diag(eigs)      → build diagonal Λ from eigenvalues
Step 3: U @ Lambda @ U.T   → reconstruct M
Step 4: np.allclose(M_reconstructed, M)  → should be True
```

In [ ]:
M_sym = np.array([[4.0, 2.0],
                  [2.0, 3.0]])   # symmetric: M == Mᵀ

# YOUR CODE
eigs, U = np.linalg.eigh(M_sym)    # eigh for symmetric
Lambda  = np.diag(eigs)             # diagonal matrix of eigenvalues

M_reconstructed = U @ Lambda @ U.T  # M = U Λ Uᵀ

print("Eigenvalues:", np.round(eigs, 4))
show("U (eigenvectors)", U)
show("Lambda", Lambda)
show("Reconstructed M = UΛUᵀ", M_reconstructed)

print("\nM == UΛUᵀ?",      np.allclose(M_sym, M_reconstructed))  # True
print("U is orthogonal?",  np.allclose(U @ U.T, np.eye(2)))       # True

---
## MODULE 7 — PCA

**Mental model:**
```
Problem: 4 correlated features → hard to visualise, redundant info
PCA solution: find the 2 directions of MOST VARIATION
              project data onto those 2 directions
              keep 92% of information with only 50% of features

The directions = eigenvectors of the covariance matrix
The variation  = eigenvalues (bigger = more important)
```

### Exercise 7-A: Variance explained

**Hint:**
```
Step 1: total variance = sum of ALL eigenvalues
Step 2: variance from k components = sum of TOP k eigenvalues
Step 3: % = (step 2 / step 1) × 100
```

In [ ]:
# Eigenvalues from the lecture example
eigenvalues = np.array([16.5, 5.4, 1.5, 0.4])   # sorted largest first

# YOUR CODE
total_var   = np.sum(eigenvalues)
var_2_PCs   = np.sum(eigenvalues[:2])    # top 2
pct_2_PCs   = var_2_PCs / total_var * 100

print(f"Total variance:         {total_var}")
print(f"Variance from 2 PCs:    {var_2_PCs}")
print(f"% explained by 2 PCs:   {pct_2_PCs:.2f}%")   # 92.02%

# Show cumulative for all components
print("\nCumulative variance explained:")
for k in range(1, 5):
    cum = np.sum(eigenvalues[:k]) / total_var * 100
    bar = '█' * int(cum // 5)
    print(f"  PC{k}: {cum:5.1f}%  {bar}")

In [ ]:
# ✅ Check
check("% explained (2 PCs)", pct_2_PCs, 92.02, tol=0.1)

### Exercise 7-B: Project a vector to lower dimensions

**Hint:**
```
Step 1: Build U by stacking u1 and u2 as ROWS → shape (2, 4)
Step 2: x_new = U @ x_old
        shape: (2,4) @ (4,) → (2,)  ← 2D result!
Step 3: PC1 = u1 · x_old,  PC2 = u2 · x_old
        (just dot products of each eigenvector with the input)
```

In [ ]:
# Eigenvectors from the lecture
u1 = np.array([0.39, 0.42, 0.44, 0.69])
u2 = np.array([0.40, 0.39, 0.42, -0.72])

# Input: a new 4D body measurement vector
x_old = np.array([0.5, 0.6, 1.6, 0.9])

# YOUR CODE

# Step 1: Build transformation matrix U (2 rows × 4 cols)
U = np.vstack([u1, u2])          # stack as rows
print("U shape:", U.shape)        # (2, 4)

# Step 2: Project
x_new = U @ x_old
print("\nx_old (4D):", x_old)
print("x_new (2D):", np.round(x_new, 4))
# expected: [1.772, ~1.04]

# Step 3: Understand what each PC means
print(f"\nPC1 = {round(x_new[0],3)} (dot of u1 with x = {round(np.dot(u1, x_old),3)})")
print(f"PC2 = {round(x_new[1],3)} (dot of u2 with x = {round(np.dot(u2, x_old),3)})")
print("\n→ We compressed 4 numbers into 2, keeping 92% of the information.")

In [ ]:
# ✅ Check
check("PC1",  x_new[0], 1.772, tol=0.01)
check("U shape rows", U.shape[0], 2)
check("U shape cols", U.shape[1], 4)

### Exercise 7-C: Full PCA pipeline from scratch

**Hint:**
```
Step 1: Mean-centre data:       X_c = X - X.mean(axis=0)
Step 2: Covariance matrix:      C = (X_c.T @ X_c) / n_samples
Step 3: Eigendecomposition:     np.linalg.eigh(C)  → sorted ascending
Step 4: Reverse order:          eigs[::-1],  vecs[:, ::-1]
Step 5: Take top k eigenvectors: Uk = vecs[:, :k]
Step 6: Project:                data_2d = X_c @ Uk
```

In [ ]:
np.random.seed(42)
n = 100

# Simulated body data: height, weight, neck, waist, age
height = np.random.normal(1.70, 0.10, n)
weight = 40 * height + np.random.normal(0, 5, n)      # correlated with height
neck   = 0.2 * weight + np.random.normal(0, 2, n)     # correlated with weight
waist  = 0.5 * weight + np.random.normal(0, 5, n)     # correlated with weight
age    = np.random.normal(40, 10, n)                   # independent

X = np.column_stack([height, weight, neck, waist, age])  # shape (100, 5)
print("Data shape:", X.shape)    # (100, 5)

# YOUR CODE — implement each step

# Step 1: Mean-centre
X_c = X - X.mean(axis=0)

# Step 2: Covariance matrix
C = (X_c.T @ X_c) / n
print("Covariance matrix shape:", C.shape)    # (5, 5)

# Step 3: Eigendecomposition
eigs, vecs = np.linalg.eigh(C)

# Step 4: Sort descending
eigs = eigs[::-1]
vecs = vecs[:, ::-1]

# Step 5: Top 2 eigenvectors
k  = 2
Uk = vecs[:, :k]         # shape (5, 2)

# Step 6: Project
data_2d = X_c @ Uk        # shape (100, 2)

print("\nTop 2 eigenvalues:",   np.round(eigs[:2], 2))
print("Variance explained: ",  round(np.sum(eigs[:2]) / np.sum(eigs) * 100, 1), "%")
print("Projected shape:",       data_2d.shape)   # (100, 2)

# Verify with sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X_std   = StandardScaler().fit_transform(X)
pca_sk  = PCA(n_components=2)
data_sk = pca_sk.fit_transform(X_std)

print("\nsklearn explained variance:",
      np.round(pca_sk.explained_variance_ratio_ * 100, 1), "%")

---
## MODULE 8 — Linear Regression: Full Pipeline

**This brings everything together:**
```
1. Data → vector/matrix form
2. Standardise → norms (Module 4)
3. Solve W* = (XXᵀ)⁻¹ XY → inverse (Module 5)
4. Predict → matrix multiply (Module 3)
5. Evaluate → norms, MSE
6. Ridge → eigenvalues ensure invertibility (Module 6)
```

### Exercise 8-A: Linear Regression from scratch

**Hint:**
```
Step 1: Standardise X:  mean = X.mean(axis=1),  std = X.std(axis=1)
                        X_sc = (X - mean[:,None]) / std[:,None]
        [:,None] reshapes (2,) to (2,1) for broadcasting

Step 2: Add bias row:   np.vstack([X_sc, np.ones((1, m))])

Step 3: Solve:          XXT = X @ X.T
                        XY  = X @ Y
                        W   = np.linalg.inv(XXT) @ XY

Step 4: Predict:        Y_pred = X.T @ W

Step 5: MSE:            np.mean((Y_pred - Y) ** 2)
```

In [ ]:
# Dataset: 4 houses  [dien_tich, so_phong]  →  gia (ty dong)
# Design matrix format: each COLUMN = one house
X_raw = np.array([[50, 80, 60, 90],    # x1: dien_tich
                  [ 2,  3,  2,  4]],   # x2: so_phong
                 dtype=float)          # shape (2, 4)

Y = np.array([[3.0],
              [4.5],
              [3.5],
              [5.5]])                  # shape (4, 1)

# YOUR CODE

# Step 1: Standardise each feature row
mean_x = X_raw.mean(axis=1)           # mean per feature → shape (2,)
std_x  = X_raw.std(axis=1)            # std  per feature → shape (2,)
X_sc   = (X_raw - mean_x[:, None]) / std_x[:, None]

print("mean:", np.round(mean_x, 4))   # [70.  2.75]
print("std: ", np.round(std_x,  4))   # [15.8114  0.8292]

# Step 2: Append bias row of 1s
X = np.vstack([X_sc, np.ones((1, X_sc.shape[1]))])   # shape (3, 4)
print("\nX (with bias):\n", np.round(X, 4))

# Step 3: Solve W* = (XXT)⁻¹ XY
XXT  = X @ X.T
XY   = X @ Y
W    = np.linalg.inv(XXT) @ XY

print("\nW* = [w1, w2, bias]ᵀ:")
print(np.round(W, 4))        # w1≈0.5534, w2≈0.4146, bias≈4.125

# Step 4: Predict
Y_pred = X.T @ W
print("\nPredicted prices:", np.round(Y_pred.flatten(), 4))
print("Actual prices:   ", Y.flatten())

# Step 5: MSE
mse = np.mean((Y_pred - Y) ** 2)
print(f"\nMSE = {mse:.6f}")   # 0.00625
print(f"RMSE = {np.sqrt(mse):.4f} ty dong ≈ {np.sqrt(mse)*1000:.0f} trieu")

In [ ]:
# ✅ Check
check("w1",   float(W[0]), 0.5534, tol=0.01)
check("w2",   float(W[1]), 0.4146, tol=0.01)
check("bias", float(W[2]), 4.125,  tol=0.01)
check("MSE",  mse,          0.00625)

### Exercise 8-B: Ridge Regression

**Hint:**
```
Only one change from Linear Regression:
  W = inv(XXT + λI) @ XY
  instead of
  W = inv(XXT) @ XY

Try different values of λ and see how W changes.
```

In [ ]:
# Reuse X, Y, XXT, XY from Exercise 8-A

print(f"{'λ':>6}  {'w1':>8}  {'w2':>8}  {'bias':>8}  {'MSE':>10}")
print("-" * 50)

for lam in [0.0, 0.1, 1.0, 5.0, 20.0]:
    # YOUR CODE: only change from linear is adding lam * I
    XXT_r  = XXT + lam * np.eye(XXT.shape[0])   # add λI
    W_r    = np.linalg.inv(XXT_r) @ XY
    Y_r    = X.T @ W_r
    mse_r  = float(np.mean((Y_r - Y)**2))
    print(f"{lam:>6.1f}  {float(W_r[0]):>8.4f}  {float(W_r[1]):>8.4f}  {float(W_r[2]):>8.4f}  {mse_r:>10.6f}")

print("""
Observations:
  λ=0.0 → same as Linear Regression
  λ↑    → w1, w2 shrink toward 0 (but never exactly 0)
  λ↑    → bias stays close to mean(Y) = 4.125
  λ↑    → train MSE increases (accepting more bias)
  λ↑    → model becomes more stable (less variance)
""")

### Exercise 8-C: Predict a new house

**Goal:** Use the trained model to predict the price of a house you've never seen.

**Hint:**
```
Step 1: Standardise new house using the SAME mean and std from training
        DO NOT recompute mean/std on the new house!
Step 2: Append 1 for bias
Step 3: y_pred = x_new.T @ W
```

In [ ]:
# Reuse W (linear regression weights) and mean_x, std_x from Exercise 8-A

# New house: 70 m², 3 bedrooms
new_raw = np.array([70.0, 3.0])

# YOUR CODE

# Step 1: Standardise with training mean and std
new_sc   = (new_raw - mean_x) / std_x       # shape (2,)
print("Standardised:", np.round(new_sc, 4))  # [0.0, 0.3015]

# Step 2: Append 1 for bias
new_ext  = np.append(new_sc, 1.0)           # shape (3,)
print("Extended:     ", np.round(new_ext, 4))

# Step 3: Predict
y_pred   = float(new_ext @ W)               # dot product
print(f"\nPredicted price: {y_pred:.4f} ty dong")
# expected: ~4.25 ty

# Sanity check: this house (70m², 3br) should cost between
# house 3 (60m², 2br → 3.5 ty) and house 2 (80m², 3br → 4.5 ty)
print("\nSanity check:")
print("  House 3 (60m², 2br) = 3.5 ty")
print(f"  NEW   (70m², 3br) = {y_pred:.2f} ty  ← should be between")
print("  House 2 (80m², 3br) = 4.5 ty")

---
## 🏆 Final Challenge — Build it yourself

**Complete this pipeline with NO hints:**

```
Dataset: 6 houses with 3 features + price
Task:
  1. Standardise (fit on first 5, transform all 6)
  2. Implement Linear Regression (W* formula)
  3. Implement Ridge Regression (λ = 1.0)
  4. Predict house #6 price with both models
  5. Compare predictions vs actual price (2.5 ty)
  6. Compute MSE for both models on training set
```

In [ ]:
# Dataset: [dien_tich, so_phong, kc_trung_tam, gia]
data = np.array([
    [50,  2,  5.0,  3.0],
    [80,  3,  3.0,  4.5],
    [60,  2, 10.0,  3.2],
    [90,  4,  2.0,  5.5],
    [70,  3,  7.0,  4.0],
    [45,  1, 15.0,  2.5],   # ← test: predict this one
], dtype=float)

X_all = data[:, :3].T     # shape (3, 6): features as rows
y_all = data[:,  3]       # shape (6,)

# Split
X_train = X_all[:, :5]    # first 5 houses
y_train = y_all[:5]
X_test  = X_all[:, 5:]    # last house
y_test  = y_all[5:]

# YOUR COMPLETE CODE BELOW
# ─────────────────────────




# Expected output:
# Actual price house #6:     2.5 ty
# Linear Regression pred:    ~2.4-2.6 ty
# Ridge Regression pred:     ~2.4-2.6 ty

---
## 📋 NumPy Cheat Sheet

| Task | Code |
|---|---|
| Create vector | `np.array([1, 2, 3])` |
| Create matrix | `np.array([[1,2],[3,4]])` |
| Shape | `x.shape` |
| Reshape | `x.reshape(3, 1)` or `x.reshape(-1, 1)` |
| Transpose | `M.T` |
| Matrix multiply | `A @ B` |
| Element-wise × | `A * B` |
| Dot product | `np.dot(x, y)` or `x @ y` |
| L2 norm | `np.linalg.norm(x)` |
| L1 norm | `np.sum(np.abs(x))` |
| Mean per row | `X.mean(axis=1)` |
| Mean per col | `X.mean(axis=0)` |
| Stack rows | `np.vstack([a, b])` |
| Stack cols | `np.hstack([a, b])` |
| Append element | `np.append(x, 1.0)` |
| Identity n×n | `np.eye(n)` |
| Diagonal matrix | `np.diag([a,b,c])` |
| Determinant | `np.linalg.det(M)` |
| Inverse | `np.linalg.inv(M)` |
| Eigenvalues | `np.linalg.eig(M)` |
| Eigenvalues (symmetric) | `np.linalg.eigh(M)` |
| Trace | `np.trace(M)` |
| Check equal | `np.allclose(A, B)` |